version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: blastmail_app
    ports:
      - "8010:8010"
    volumes:
      - .:/var/www/html:cached       # código do projeto
      - blastmail_vendor:/var/www/html/vendor   # dependências PHP isoladas
    working_dir: /var/www/html
    command: php -S 0.0.0.0:8010 -t public
    depends_on:
      - node
    environment:
      - PHP_IDE_CONFIG=serverName=blastmail
    networks:
      - blastmail_net

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: blastmail_node
    volumes:
      - .:/var/www/html:cached
      - blastmail_node_modules:/var/www/html/node_modules
    working_dir: /var/www/html
    command: npm run dev -- --host
    ports:
      - "5173:5173"
    networks:
      - blastmail_net

networks:
  blastmail_net:
    driver: bridge

volumes:
  blastmail_vendor:
  blastmail_node_modules:
